services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\Sessionplaner\:
    resource: '../Classes/*'

  Evoweb\Sessionplaner\Controller\AjaxController:
    public: true

  Evoweb\Sessionplaner\Domain\Factory\SuggestFormFactory:
    public: true

  Evoweb\Sessionplaner\Domain\Finisher\SuggestFormFinisher:
    public: true
