name: build

on:
  push:
    branches: [ develop, main ]
    tags: [ '*' ]
  pull_request:
    branches: [ develop ]

jobs:
  resources:
    name: Resources tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Run the scss lint
        run: Build/Scripts/runTests.sh -s lintScss

      - name: Install
        run: |
          Build/Scripts/runTests.sh \
            -p 8.4 \
            -s composerInstall

      - name: Run the phpstan
        run: |
          Build/Scripts/runTests.sh \
            -p 8.4 \
            -s phpstan

      - name: Run the cgl lint
        run: |
          Build/Scripts/runTests.sh \
            -p 8.4 \
            -s cgl

      - name: Run the xliff lint
        run: |
          Build/Scripts/runTests.sh \
            -p 8.4 \
            -s checkIntegrityXliff

      - name: Test documentation build
        run: |
          Build/Scripts/runTests.sh \
            -p 8.4 \
            -s checkRstRenderingSingle

  testsuite:
    name: All php tests for TYPO3 ${{ matrix.packages.core }} with PHP ${{ matrix.packages.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
        prefer: ['', '--prefer-lowest']
        packages:
          - core: '^13.4'
            framework: '^9.2.1'

          - core: '^14.3'
            framework: '^9.5.0'

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: PHP lint
        run: |
          Build/Scripts/runTests.sh \
            -p ${{ matrix.php }} \
            -s lintPhp

      - name: Composer install core
        run: |
          Build/Scripts/runTests.sh \
            -p ${{ matrix.php }} \
            -s composer require ${{ matrix.prefer }} "typo3/cms-core:${{ matrix.packages.core }}"

      - name: Composer validate
        run: |
          Build/Scripts/runTests.sh \
            -p ${{ matrix.php }} \
            -s composerValidate

  TERUpload:
    needs: [ resources, testsuite ]
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    name: TYPO3 TER release
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Publish to TER
        uses: tomasnorre/typo3-upload-ter@v2
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}
